# Generated by Django 4.2.5 on 2024-03-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0002_historia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.AlterModelOptions(
            name='historia',
            options={'ordering': ['titulo'], 'verbose_name': 'historia', 'verbose_name_plural': 'historias'},
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['titulo'], 'verbose_name': 'receta', 'verbose_name_plural': 'recetas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nomUsuario'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
