# Generated by Django 4.2.5 on 2024-03-28 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0003_alter_categoria_options_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
