# Generated by Django 4.2.5 on 2024-03-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
