# Generated by Django 4.2.5 on 2024-03-29 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0009_delete_categoria_delete_comentario_historia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='descripcionBreve',
            field=models.TextField(default='Valor predeterminado', max_length=180),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaPublicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
