# Generated by Django 4.2.5 on 2024-03-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0010_historia_descripcionbreve_historia_fechapublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagenReceta',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
