# Generated by Django 4.2.5 on 2024-03-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0011_alter_receta_imagenreceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagenReceta',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
